<?php
/**
 * Created by PhpStorm.
 * User: drupalviking
 * Date: 11/06/15
 * Time: 11:04
 */
?>
<h1>Þingmál <?=$this->issue->issue_id . "/" . $this->issue->assembly_id . " - " . ucfirst($this->issue->name); ?></h1>
<h2><?=$this->issue->type_name;?></h2>
<p><strong>Staða: </strong><?=$this->issue->status; ?></p>
<dl>
  <dt>Fjöldi ræða:</dt>
  <dd><?=$this->speech_meta['speechCount']; ?></dd>
  <dt>Heildarræðutími:</dt>
  <dd><?=$this->time($this->speech_meta['totalSpeechTime']); ?></dd>
</dl>

<h2>Ræðutími, brotinn niður eftir flokkum</h2>
<table>
  <thead>
    <tr>
      <td>Flokkur</td>
      <td>Ræðutími</td>
    </tr>
  </thead>
  <tbody>
  <?php foreach($this->speech_meta['speechTimeByParties'] as $speechTime) : ?>
    <tr>
      <td><?=$speechTime->party; ?></td>
      <td><?=$this->time($speechTime->speech_time); ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<p><a href="<?=$this->url('speech/index',array('issue_id' => $this->issue->id, 'assembly_id'=>$this->issue->assembly_id));?>">Ræður málsins</a></p>
<h2>Atkvæðagreiðslur</h2>
<table>
  <thead>
    <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
      <td>Nefnd</td>
      <td>Já</td>
      <td>Nei</td>
      <td>Sat hjá</td>
      <td>Niðurstaða</td>
      <td>Skjal</td>
    </tr>
  </thead>
  <tbody>
    <?php foreach($this->votes as $vote) : ?>
      <tr>
        <td><?=$vote->progress_type; ?></td>
        <td><?=$vote->vote_type;?></td>
        <td><?=$vote->more;?></td>
        <td><?=$vote->commitee;?></td>
        <td><?=$vote->yes;?></td>
        <td><?=$vote->no;?></td>
        <td><?=$vote->abstrained; ?></td>
        <td><?=$vote->result;?></td>
        <td><?=$vote->document_id;?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>